### ISSUE TITLE
コードのコメント

### ISSUE THREAD

**Issue by Miura55** [ymd65536/cloudtech_quiz_bot#1]
コードを見ていて気になったことをコメントします。確認をお願いします。

# リッチメニューの実装
- Slackではリッチメニューの操作はBot上でやるものだと言ってしまいましたが、Bot上でやるのは `設定済みのリッチメニューの表示を切り替える`ことだけで、それ以前のリッチメニューの作成(画像やリッチメニューの配置設定)は流石にBotを動かす前に１回だけやるほうがいいです(言葉不足ですみません)。リッチメニューの作成には1000件の上限があるので気をつけてください。

https://developers.line.biz/ja/reference/messaging-api/#delete-rich-menu

- requestsを使っていますが、line-bot-sdkにはリッチメニューを設定するSDKがあるのでできればそっちを使ってほしいです

https://github.com/line/line-bot-sdk-python/blob/master/README.rst#create_rich_menuself-rich_menu-timeoutnone

# Lambdaの実装について
- Scoreモデルを作っていますが、このモデルってコードでは一つも使ってなくて、boto3を使ってテーブルを参照してますよね？変更途中であれば大丈夫ですが、もし使う予定が無いのであれば削除してほしいです。

https://github.com/ymd65536/cloudtech_quiz_bot/blob/62cbd019eeb8ad64678d07f1b2e43fce47c51207/lambda_function.py#L19-L24

- score_model.py がありますが、これは必要なものですか？

**Comment by ymd65536** [comment]
レビューありがとうございます。

Lambdaの実装については解消しました。
確かに
DynamoDBのマイグレーションスクリプトでモデルを作成するときだけ利用しているので
bot には不要です。
ご指摘ありがとうございます。

**Comment by ymd65536** [comment]
> # Lambdaの実装について
> * Scoreモデルを作っていますが、このモデルってコードでは一つも使ってなくて、boto3を使ってテーブルを参照してますよね？変更途中であれば大丈夫ですが、もし使う予定が無いのであれば削除してほしいです。
> 
> https://github.com/ymd65536/cloudtech_quiz_bot/blob/62cbd019eeb8ad64678d07f1b2e43fce47c51207/lambda_function.py#L19-L24
> 
> * score_model.py がありますが、これは必要なものですか？

レビューありがとうございます。

Lambdaの実装については解消しました。
確かに
DynamoDBのマイグレーションスクリプトでモデルを作成するときだけ利用しているので
bot には不要です。
ご指摘ありがとうございます。
